### ISSUE TITLE
MSW를 사용한 모킹에서 asset을 불러올 때 콘솔 오류를 해결한다.

### ISSUE THREAD

**Issue by sshrik** [lucky-treee/poom-fe#31]
**Background**

현재 msw 라이브러리를 사용해서 구현되지 않은 API를 모킹하고 있다. 그러나 구현되지 않은 API만 모킹하는 것이 아니라, 모든 asset에 대한 요청들도 모킹하는 Handler를 찾으면서 콘솔에 오류가 발생한다.

**Acceptance Criteria**

모킹하는 API가 아닌 다른 요청은 msw 모킹에서 확인하지 않아야 한다.

**Comment by m1nsuppp** [comment]
현준님~~ 혹시 이 에러에 대한 콘솔창을 한 번 확인해볼 수 있을까요?~!
